version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  purchases:
    build:
      context: ./SalesHandler      # ← проверь, что папка называется именно так
    ports:
      - "5050:80"
    depends_on:
      - postgres
      - rabbitmq

  settlements:
    build:
      context: ./BillingHandler    # ← поправь, если другое имя каталога
    ports:
      - "5001:80"
    depends_on:
      - postgres
      - rabbitmq

  gateway:
    build:
      context: ./EdgeGateway
    ports:
      - "8080:8080"
    depends_on:
      - purchases
      - settlements

